// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["react", "Field"], function(React, Field) {
    var Output;
    return Output = (function(superClass) {
      extend(Output, superClass);

      Output.prototype.el = '';

      function Output(props) {
        Output.__super__.constructor.call(this, props);
      }

      Output.prototype.render = function() {
        var i, k, v;
        i = 0;
        return React.createElement("div", {
          "className": "Output"
        }, React.createElement("br", null), (function() {
          var ref, results;
          ref = this.props.output;
          results = [];
          for (k in ref) {
            v = ref[k];
            results.push(React.createElement(Field, {
              "key": i++,
              "field": k,
              "type": "Output",
              "node": this.props.node
            }));
          }
          return results;
        }).call(this));
      };

      return Output;

    })(React.Component);
  });

}).call(this);

//# sourceMappingURL=Output.map
