// Generated by CoffeeScript 1.10.0
(function() {
  define('Actions', [''], function() {
    var addConnection, addNode, setPos, startConnecting, startDragging, stopConnecting, stopDragging;
    addNode = function(nodeType, pos, input) {
      return {
        type: 'ADD_NODE',
        nodeType: nodeType,
        pos: pos,
        input: input
      };
    };
    setPos = function(node, pos) {
      return {
        type: 'SET_POS',
        id: node,
        pos: pos
      };
    };
    startConnecting = function(node, field, type) {
      return {
        type: 'START_CONNECTING',
        node: node,
        field: field,
        fieldType: type
      };
    };
    stopConnecting = function() {
      return {
        type: 'STOP_CONNECTING'
      };
    };
    startDragging = function(id) {
      return {
        type: 'START_DRAGGING',
        id: id
      };
    };
    stopDragging = function(id) {
      return {
        type: 'STOP_DRAGGING',
        id: id
      };
    };
    addConnection = function(Input, Output) {
      return {
        type: 'ADD_CONNECTION',
        Input: Input,
        Output: Output
      };
    };
    return {
      addNode: addNode,
      setPos: setPos,
      startDragging: startDragging,
      stopDragging: stopDragging,
      startConnecting: startConnecting,
      stopConnecting: stopConnecting,
      addConnection: addConnection
    };
  });

}).call(this);

//# sourceMappingURL=Actions.map
