// Generated by CoffeeScript 1.10.0
(function() {
  define('Actions', [''], function() {
    var addConnection, addNode, setPos, startConnecting, startDragging, stopConnecting, stopDragging, updateNode;
    addNode = function(nodeType, pos, input, output) {
      return {
        type: 'ADD_NODE',
        nodeType: nodeType,
        pos: pos,
        input: input,
        output: output
      };
    };
    setPos = function(node, pos) {
      return {
        type: 'SET_POS',
        id: node,
        pos: pos
      };
    };
    startConnecting = function(node, field, type) {
      return {
        type: 'START_CONNECTING',
        node: node,
        field: field,
        fieldType: type
      };
    };
    stopConnecting = function() {
      return {
        type: 'STOP_CONNECTING'
      };
    };
    updateNode = function(node, inputs, outputs, cons) {
      return {
        type: 'UPDATE_NODE',
        node: node,
        inputs: inputs,
        outputs: outputs,
        outputFields: cons.map(function(con) {
          return con.Output.Field;
        }),
        connectedNodes: cons.map(function(con) {
          return con.Input.Node;
        }),
        connectedFields: cons.map(function(con) {
          return con.Input.Field;
        })
      };
    };
    startDragging = function(id) {
      return {
        type: 'START_DRAGGING',
        id: id
      };
    };
    stopDragging = function(id) {
      return {
        type: 'STOP_DRAGGING',
        id: id
      };
    };
    addConnection = function(Input, Output) {
      return {
        type: 'ADD_CONNECTION',
        Input: Input,
        Output: Output
      };
    };
    return {
      addNode: addNode,
      setPos: setPos,
      startDragging: startDragging,
      stopDragging: stopDragging,
      startConnecting: startConnecting,
      stopConnecting: stopConnecting,
      addConnection: addConnection,
      updateNode: updateNode
    };
  });

}).call(this);

//# sourceMappingURL=Actions.map
