// Generated by CoffeeScript 1.9.3
(function() {
  require.config({
    paths: {
      jquery: "lib/jquery-3.1.0.min",
      react: "lib/react",
      ReactDOM: "lib/react-dom",
      three: "lib/three.min",
      UI: "UI",
      Node: "NodeTypes/Node",
      TestNode: "NodeTypes/TestNode"
    }
  });

  require(['Node', 'UI', 'react', 'ReactDOM'], function(Node, UI, React, ReactDOM) {
    var root;
    root = React.createElement(Node, {
      name: "test"
    });
    return ReactDOM.render(root, document.getElementById('Editor'));
  });

}).call(this);

//# sourceMappingURL=App.js.map
