// Generated by CoffeeScript 1.10.0
require.config({
  paths: {
    react: "lib/react-with-addons",
    ReactDOM: "lib/react-dom",
    redux: "lib/redux",
    reactredux: "lib/react-redux",
    three: "lib/three.min",
    UI: "UI",
    Node: "NodeTypes/Node",
    TestNode: "NodeTypes/TestNode",
    Editor: "Editor",
    Reducer: "Reducer",
    Actions: "Actions"
  }
});

require(['redux', 'Reducer', 'Editor', 'react', 'ReactDOM', 'reactredux'], (function(_this) {
  return function(T, Reducer, Editor, React, ReactDOM, A) {
    var Provider, createStore, store;
    createStore = require('redux').createStore;
    Provider = require('reactredux').Provider;
    store = createStore(Reducer, window.devToolsExtension && window.devToolsExtension());
    return ReactDOM.render(React.createElement(Provider, {
      "store": store
    }, React.createElement(Editor, null)), document.getElementById("container"));
  };
})(this));

//# sourceMappingURL=App.map
