// Generated by CoffeeScript 1.10.0
var initialState,
  slice = [].slice;

initialState = {
  Nodes: []
};

define(['redux'], function() {
  var Nodes, combineReducers;
  combineReducers = require('redux').combineReducers;
  Nodes = function(state, action) {
    if (state == null) {
      state = [];
    }
    switch (action.type) {
      case 'ADD_NODE':
        return slice.call(state).concat([{
            nodeType: action.nodeType,
            pos: action.pos
          }]);
    }
    return state;
  };
  return combineReducers({
    Nodes: Nodes
  });
});

//# sourceMappingURL=Reducer.map
