// Generated by CoffeeScript 1.10.0
(function() {
  var initialState,
    slice = [].slice;

  initialState = {
    Nodes: [],
    Connecting: false,
    Connections: [],
    SelectedNode: -1,
    SelectedField: ''
  };

  define(['redux'], function() {
    var Connecting, Connections, Dragging, Node, Nodes, Selected, combineReducers;
    combineReducers = require('redux').combineReducers;
    Node = function(state, action) {
      if (state == null) {
        state = {
          nodeType: '',
          id: -1,
          pos: {
            x: -1,
            y: -1
          },
          Connections: [],
          dragging: false
        };
      }
      switch (action.type) {
        case 'ADD_NODE':
          return {
            nodeType: action.nodeType,
            id: action.id,
            pos: action.pos,
            Connections: [],
            dragging: false
          };
        case 'SET_POS':
          if (state.id !== action.id) {
            return state;
          }
          return Object.assign({}, state, {
            pos: action.pos,
            dragging: false
          });
        case 'ADD_CONNECTION':
          if (state.id === action.Input.Node || state.id === action.Output.Node) {
            return Object.assign({}, state, {
              Connections: slice.call(state.Connections).concat([action.id])
            });
          }
          break;
        case 'START_DRAGGING':
          if (state.id === action.id) {
            return Object.assign({}, state, {
              dragging: true
            });
          }
          break;
        case 'STOP_DRAGGING':
          if (state.id === action.id) {
            return Object.assign({}, state, {
              dragging: false
            });
          }
      }
      return state;
    };
    Nodes = function(state, action) {
      if (state == null) {
        state = [];
      }
      switch (action.type) {
        case 'ADD_NODE':
          return slice.call(state).concat([Node(void 0, action)]);
        case 'SET_POS':
        case 'SET_VAL':
        case 'ADD_CONNECTION':
        case 'START_DRAGGING':
        case 'STOP_DRAGGING':
          return state.map((function(_this) {
            return function(t) {
              return Node(t, action);
            };
          })(this));
      }
      return state;
    };
    Connections = function(state, action) {
      if (state == null) {
        state = [];
      }
      switch (action.type) {
        case 'ADD_CONNECTION':
          return slice.call(state).concat([{
              id: action.id,
              Input: action.Input,
              Output: action.Output
            }]);
      }
      return state;
    };
    Connecting = function(state, action) {
      if (state == null) {
        state = false;
      }
      switch (action.type) {
        case 'START_CONNECTING':
          return true;
        case 'STOP_CONNECTING':
          return false;
      }
      return state;
    };
    Selected = function(state, action) {
      if (state == null) {
        state = {
          Node: -1,
          Field: '',
          Type: ''
        };
      }
      switch (action.type) {
        case 'START_CONNECTING':
          return {
            Node: action.node,
            Field: action.field,
            Type: action.fieldType
          };
      }
      return state;
    };
    Dragging = function(state, action) {
      if (state == null) {
        state = false;
      }
      switch (action.type) {
        case 'START_DRAGGING':
          return true;
        case 'STOP_DRAGGING':
          return false;
      }
      return state;
    };
    return combineReducers({
      Nodes: Nodes,
      Connections: Connections,
      Connecting: Connecting,
      Selected: Selected,
      Dragging: Dragging
    });
  });

}).call(this);

//# sourceMappingURL=Reducer.map
