// Generated by CoffeeScript 1.10.0
(function() {
  var initialState,
    slice = [].slice;

  initialState = {
    Nodes: [],
    Connecting: false,
    Connections: [],
    SelectedNode: -1,
    SelectedField: ''
  };

  define(['redux'], function() {
    var Connecting, Node, Nodes, Selected, combineReducers;
    combineReducers = require('redux').combineReducers;
    Node = function(state, action) {
      if (state == null) {
        state = {
          nodeType: '',
          id: -1,
          pos: {
            x: -1,
            y: -1
          }
        };
      }
      switch (action.type) {
        case 'ADD_NODE':
          return {
            nodeType: action.nodeType,
            id: action.id,
            pos: action.pos
          };
        case 'SET_POS':
          if (state.id !== action.id) {
            return state;
          }
          return Object.assign({}, state, {
            pos: action.pos
          });
      }
      return state;
    };
    Nodes = function(state, action) {
      if (state == null) {
        state = [];
      }
      switch (action.type) {
        case 'ADD_NODE':
          return slice.call(state).concat([Node(void 0, action)]);
        case 'SET_POS':
          return state.map((function(_this) {
            return function(t) {
              return Node(t, action);
            };
          })(this));
      }
      return state;
    };
    Connecting = function(state, action) {
      if (state == null) {
        state = false;
      }
      switch (action.type) {
        case 'SELECT':
          return true;
        case 'STOP_CONNECTING':
          return false;
      }
      return state;
    };
    Selected = function(state, action) {
      if (state == null) {
        state = {
          Node: -1,
          Field: '',
          Type: ''
        };
      }
      switch (action.type) {
        case 'SELECT':
          return {
            Node: action.node,
            Field: action.field,
            Type: action.fieldType
          };
      }
      return state;
    };
    return combineReducers({
      Nodes: Nodes,
      Connecting: Connecting,
      Selected: Selected
    });
  });

}).call(this);

//# sourceMappingURL=Reducer.map
