// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["jquery", "react"], function($, React) {
    var ExampleComponent;
    return ExampleComponent = (function(superClass) {
      extend(ExampleComponent, superClass);

      function ExampleComponent(props) {
        ExampleComponent.__super__.constructor.call(this, props);
        this.state = {
          test: 123
        };
      }

      ExampleComponent.defaultProps = function() {
        return {
          bar: 'baz'
        };
      };

      ExampleComponent.prototype.render = function() {
        var n;
        return React.createElement("div", {
          "className": "neat-component"
        }, (this.props.showTitle ? React.createElement("h1", null, "A Component is I") : void 0), React.createElement("hr", null), (function() {
          var i, results;
          results = [];
          for (n = i = 1; i <= 5; n = ++i) {
            results.push(React.createElement("p", {
              "key": n
            }, "This line has been printed ", n, " times"));
          }
          return results;
        })());
      };

      return ExampleComponent;

    })(React.Component);
  });

}).call(this);

//# sourceMappingURL=Node.map
