// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["jquery", "react"], function($, React) {
    var ExampleComponent;
    return ExampleComponent = (function(superClass) {
      extend(ExampleComponent, superClass);

      function ExampleComponent(props) {
        ExampleComponent.__super__.constructor.call(this, props);
        this.state = {
          test: 123
        };
      }

      ExampleComponent.defaultProps = function() {
        return {
          bar: 'baz'
        };
      };

      ExampleComponent.prototype.render = function() {
        return React.createElement('li', null, 'First Text Content' + this.props.name);
      };

      return ExampleComponent;

    })(React.Component);
  });

}).call(this);

//# sourceMappingURL=Node.js.map
