// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['Node'], function(Node) {
    var TestNode;
    return TestNode = (function(superClass) {
      extend(TestNode, superClass);

      TestNode.prototype.name = 'Test Node';

      function TestNode(x, y) {
        TestNode.__super__.constructor.call(this, x, y);
      }

      TestNode.prototype.input = {
        TestInput: "Test"
      };

      TestNode.prototype.center = "Test Center";

      TestNode.prototype.output = {
        TestOutput: "Test"
      };

      return TestNode;

    })(Node);
  });

}).call(this);

//# sourceMappingURL=TestNode.map
